-- Made with SQL Wizard
\c testDB2

GRANT USAGE ON SCHEMA public TO JoeBiden;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO JoeBiden;
\c testDB1

GRANT USAGE ON SCHEMA public TO JoeBiden;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO JoeBiden;
GRANT CONNECT ON DATABASE testDB2 TO JoeBiden;
GRANT CONNECT ON DATABASE testDB1 TO JoeBiden;
CREATE USER JoeBiden WITH PASSWORD 'JOEBIDEN1';